all:
  .settings:
    select2_web_dir:    /sfSelect2WidgetsPlugin/select2
    available_cultures: [ ar, bg, ca, cs, da, de, el, en, es, et, eu, fa, fi, fr, gl, he, hr, hu, id, is, it, ja, ka, ko, lt, lv, mk, ms, nl, no, pl, pt-BR, pt-PT, ro, rs, ru, sk, sv, th, tr, uk, vi, zh-CN, zh-TW ]
